part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => FIcons(
  arrowLeft: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.arrowLeft, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  calendar: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.calendar, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  check: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.check, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  chevronDown: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.chevronDown, semanticLabel: semanticsLabel),
    ),
  ),
  chevronLeft: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.chevronLeft, semanticLabel: semanticsLabel),
    ),
  ),
  chevronRight: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.chevronRight, semanticLabel: semanticsLabel),
    ),
  ),
  chevronUp: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.chevronUp, semanticLabel: semanticsLabel),
    ),
  ),
  chevronsUpDown: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.selector, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  circleAlert: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.alertCircle, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  clock4: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.clockHour4, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  ellipsis: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.dots, semanticLabel: semanticsLabel),
    ),
  ),
  error: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.alertCircle, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  eye: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.eye, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  eyeClosed: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.eyeOff, semanticLabel: semanticsLabel),
    ),
  ),
  gripHorizontal: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.gripHorizontal, semanticLabel: semanticsLabel),
    ),
  ),
  gripVertical: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.gripVertical, semanticLabel: semanticsLabel),
    ),
  ),
  loader: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.loader, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  loaderCircle: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.loader2, semanticLabel: semanticsLabel),
    ),
  ),
  loaderPinwheel: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: 1.1,
        child: Icon(TablerIcons.windmill, semanticLabel: semanticsLabel),
      ),
    ),
  ),
  search: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.search, semanticLabel: semanticsLabel),
    ),
  ),
  userRound: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.userCircle, semanticLabel: semanticsLabel),
    ),
  ),
  x: (_, {semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Icon(TablerIcons.x, semanticLabel: semanticsLabel),
    ),
  ),
);
